Italian Language for Advanced Accessories
KB-GModStore/gmodstore-languages pull request #90
Opened 2024-06-09 18:45 UTC by AlexandreVea

```
AAS = AAS or {}
AAS.Language = AAS.Language  or {}

AAS.Language["it"] = {
    ["cancel"] = "Annulla",
    ["save"] = "Salva",
    ["name"] = "Nome",
    ["model"] = "Modello",
    ["itemPrice"] = "Prezzo",
    ["itemPos"] = "Posizione",
    ["itemStat"] = "Statistiche",
    ["itemJob"] = "Esclusivo per il mestiere",
    ["itemName"] = "Nome dell'oggetto",
    ["customCharacter"] = "Personalizza il tuo personaggio",
    ["adminDashboard"] = "PANNELLO DI AMMINISTRAZIONE",
    ["welcomeText"] = "BENVENUTO, COSA DESIDERI ACQUISTARE?",
    ["position"] = "POSIZIONE",
    ["rotation"] = "ROTATIONE",
    ["scale"] = "DIMENSIONE",
    ["description"] = "Una breve descrizione del tuo accessorio",
    ["search"] = "Cerca...",
    ["sell"] = "Vendere",
    ["buy"] = "Comprare",
    ["buyaccessory"] = "Acquista l'accessorio",
    ["sellaccessory"] = "Vendi l'accessorio",
    ["sure"] = "Sei sicuro di voler fare questo?",
    ["activate"] = "Attiva",
    ["desactivate"] = "Disattiva",
    ["modifypos"] = "Modifica la posizione",
    ["edititem"] = "Modifica l'oggetto",
    ["appearance"] = "Aspetto",
    ["skin"] = "Skin",
    ["desc"] = "Descrizione",
    ["titleactivate"] = "Attiva / Disattiva l'accessorio",
    ["choosecategory"] = "Scegli una categoria",
    ["chooseskin"] = "Scegli la skin",
    ["additem"] = "Aggiungi oggetto",
    ["adminname"] = "Il nome dell'accessorio non è corretto!",
    ["faildesc"] = "La descrizione non è corretta!",
    ["failprice"] = "Il prezzo non è corretto!",
    ["choosemodel"] = "Si prega di scegliere un modello",
    ["failcategory"] = "Devi scegliere una categoria",
    ["updateItem"] = "Accessorio aggiornato",
    ["deleteItem"] = "Accessorio eliminato",
    ["ownedItem"] = "Possiedi già questo accessorio",
    ["notEnoughtMoney"] = "Non hai abbastanza soldi!",
    ["notRank"] = "Non hai i permessi necessari!",
    ["itemDesactivate"] = "Questo accessorio è attualmente disattivato!",
    ["sellItem"] = "Hai venduto questo accessorio per",
    ["cantEquip"] = "Non puoi equipaggiare questo accessorio!",
    ["itemVip"] = "Questo accessorio è riservato ai membri VIP",
    ["jobProblem"] = "Il tuo lavoro attuale non ti permette di fare questo!",
    ["exploitArmory"] = "Sei troppo lontano dall'armeria per fare questo!",
    ["exploitNpc"] = "Sei troppo lontano dal NPC per fare questo!",
    ["saveBodygroup"] = "Aspetto del personaggio salvato!",
    ["addItem"] = "Accessorio aggiunto",
    ["buyItem"] = "Accessorio acquistato",
    ["for"] = "per",
    ["noItems"] = "Non ci sono accessori in vendita \n Contatta un responsabile del server!",
    ["yourInventory"] = "IL TUO INVENTARIO",
    ["emptyInventory"] = "Non hai accessori disponibili",
    ["changeInv"] = "Puoi cambiare il tuo",
    ["clickingHere"] = "cliccando qui!",
    ["upHere"] = "Cosa vorresti scegliere oggi?",
    ["equipItem"] = "Hai appena equipaggiato l'accessorio!",
    ["deequipedItem"] = "Hai appena disequipaggiato l'accessorio!",
    ["equipModel"] = "Aspetto modificato!",
    ["saveModel"] = "Salva il modello",
    ["toomany"] = "Non hai più abbastanza spazio nel tuo zaino per acquistare questo.",
    ["backpack"] = "Zaino",
    ["bought"] = "Posseduto",
    ["comboskin"] = "Scegli una skin",
    ["combocategory"] = "Scegli una categoria",
    ["waitItem"] = "Attendere prima di equipaggiare un altro accessorio.",
    ["waitEquip"] = "Stai equipaggiando l'accessorio...",
    ["swepcantgo"] = "Non puoi accedere al menu con il SWEP in mano!",
    ["iconPos"] = "Modifica la posizione dell'icona",
    ["iconFov"] = "Modifica il FOV dell'icona",
    ["itemUniqueId"] = "ID Unico dell'Oggetto",
    ["adjustAccessory"] = "Regola l'oggetto",
    ["adjust"] = "Regola",
    ["adjustText"] = "Vuoi regolare l'oggetto?",
    ["notOwned"] = "Non hai acquistato l'oggetto!",
    ["rankBlackList"] = "Rango nella lista nera",

    ["titleGingerBread"] = "Pan di zenzero",
    ["titleCap"] = "Cappellino",
    ["titleHeadphones"] = "Cuffie",
    ["titleHawkMask"] = "Maschera di falco",
    ["titleBeret"] = "Berretto",
    ["titleBandMask"] = "Maschera",
    ["titlePinguin"] = "Maschera di pinguino",
    ["titleMummyMask"] = "Maschera di mummia",
    ["titleBandana"] = "Bandana",
    ["titleBag"] = "Sacca",
    ["titleMonkeyMask"] = "Maschera di scimmia",
    ["titleNinjaMask"] = "Maschera da ninja",
    ["titleZombieMask"] = "Maschera da zombie",
    ["titlePleaseStop"] = "Maschera 'stop'",
    ["titleSkullMask"] = "Maschera teschio",
    ["titleGentlemanshat"] = "Cappello da gentiluomo",
    ["titleMaskDoctor"] = "Maschera da dottore",
    ["titleOrangeHat"] = "Cappello arancione",
    ["titleBlackBagPack"] = "Zaino nero",
    ["titlePigHat"] = "Cappello maiale",
    ["titleCap2"] = "Cappellino",
    ["titleBigBagpack"] = "Zaino grande",
    ["titleSchoolBagPack"] = "Zaino scolastico",
    ["titleBeerHat"] = "Cappello birra",
    ["titleArmor"] = "Giubbotto antiproiettile",
    ["titleMaskDuck"] = "Maschera anatra",
    ["titleGlasses"] = "Occhiali",
    ["titleGlasses2"] = "Occhiali",
    ["titleAfro"] = "Afro",
    ["titleMarioHat"] = "Cappello Mario",
    ["titleGlasses3"] = "Occhiali",
    ["titleLuigiHat"] = "Cappello Luigi",
    ["titleGlasses4"] = "Occhiali",
    ["titleGlasses5"] = "Occhiali",
    ["titleToadHat"] = "Cappello Toad",
    ["titleServboHead"] = "Testa di Servbot",
    ["titleCatHat"] = "Cappello gatto",
    ["titleStrawHat"] = "Cappello di paglia",
    ["titleRabbitEar"] = "Orecchie di coniglio",
    ["titleSunHat"] = "Cappello da sole",
    ["title3DGlasses"] = "Occhiali 3D",
    ["titleCatsEars"] = "Orecchie di gatto",
    ["titleCatHat2"] = "Cappello gatto",
    ["titleJasonMask"] = "Maschera di Jason",
    ["titleMustache"] = "Baffi",
    ["titleCowboyHat"] = "Cappello da cowboy",
    ["titleDeadmau5"] = "Maschera Deadmau5",
    ["titleFrogHat"] = "Cappello rana",
    ["titleHeartBand"] = "Fascia cuore",
    ["titlePumpkinHead"] = "Testa di zucca",
    ["titleChristmasHat"] = "Cappello natalizio",
    ["titleStarHeadband"] = "Fascia stellata",
    ["titleThomasHat"] = "Cappello Thomas",
    ["titleSombrero"] = "Sombrero",
    ["titleHeadphones2"] = "Cuffie",
    ["titleSnowGoggles"] = "Occhiali da neve",
    ["titleCap3"] = "Cappellino",
    ["titleHat"] = "Cappello nero",
    ["titleGlasses6"] = "Occhiali",
    ["titleCap4"] = "Cappellino",
    ["titleDrinkCap"] = "Cappello bevanda",
    ["titleStarGlasses"] = "Occhiali stellari",
    ["titleCatEars"] = "Orecchie di gatto",
    ["titleHat2"] = "Cappello",
    ["titleBabyRhino"] = "Bebé rinoceronte",
    ["titleArnoldMask"] = "Maschera di Arnold",
    ["titleChuckMask"] = "Maschera di Chuck",
    ["titleDeerMask"] = "Maschera di cervo",
    ["titlePandaMask"] = "Maschera di panda",
    ["titleMonkeyMask2"] = "Maschera di scimmia",
    ["titleBearMask"] = "Maschera di orso",
    ["titlePigMask"] = "Maschera di maiale",
    ["titlePolishBeret"] = "Berretto polacco",
    ["titlePolishBeret2"] = "Berretto polacco",
    ["titlePolishBeret3"] = "Berretto polacco",
    ["titleBikeHelmet"] = "Casco da moto",
    ["titleBikeHelmet2"] = "Casco da moto",
    ["titleBikeHelmet3"] = "Casco da moto",
    ["titleBikeHelmet4"] = "Casco da moto",
    ["titleBikeHelmet5"] = "Casco da moto",
    ["titleBikeHelmet6"] = "Casco da moto",
    ["titleBikeHelmet7"] = "Casco da moto",
    ["titleBikeHelmet8"] = "Casco da moto",
    ["titleBikeHelmet9"] = "Casco da moto",
    ["titleBikeHelmet10"] = "Casco da moto",
    ["titleBikeHelmet11"] = "Casco da moto",
    ["titleBikeHelmet12"] = "Casco da moto",
    ["titleBikeHelmet13"] = "Casco da moto",
    ["titleBikeHelmet14"] = "Casco da moto",
    ["titleBikeHelmet15"] = "Casco da moto",
    ["titlePumpkinMask"] = "Maschera di zucca",
    ["titleHorseMask"] = "Maschera di cavallo",
    ["titleHorseMask2"] = "Maschera di cavallo",
    ["titleHorseMask3"] = "Maschera di cavallo",
    ["titleRussianHat"] = "Cappello russo",

    ["descGingerBread"] = "Un bel pan di zenzero" [...]

2024-06-10 17:13 UTC, hugoheml requested changes
Hey,
Thanks for your contribution!
In order to release it, you just need to fix a little problem

2024-06-10 17:13 UTC, hugoheml commented on zeros_farmer/zfa_languages/sh_language_it.lua
You need to change the "fr" to "it" here

2024-06-11 14:51 UTC, AlexandreVea commented on zeros_farmer/zfa_languages/sh_language_it.lua
It's good !

2024-06-16 16:01 UTC, hugoheml approved these changes
Perfect, thanks for your updates

2024-06-16 16:01 UTC, merged